# Generated by Django 5.1.3 on 2025-06-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="question", options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="question",
            name="model",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="model_type",
            field=models.CharField(
                blank=True,
                choices=[("text", "Text"), ("code", "Code"), ("image", "Image")],
                max_length=10,
                null=True,
            ),
        ),
    ]
