# Generated by Django 5.1.3 on 2025-06-07 23:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0002_alter_answer_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.ImageField(upload_to="generated/")),
                ("prompt", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
