# Generated by Django 5.1.3 on 2025-06-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0003_generatedimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generatedimage", options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
