# Generated by Django 5.1.3 on 2025-09-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="kassapayment",
            name="capture_idem_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
