# Generated by Django 5.1.3 on 2025-09-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(db_index=True, max_length=64)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("applied", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-received_at",),
            },
        ),
    ]
