# Generated by Django 5.1.3 on 2025-09-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mermind", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagram",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.AlterModelOptions(
            name="diagramrevision",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="diagram",
            name="language",
            field=models.CharField(db_index=True, default="ru", max_length=8),
        ),
        migrations.AddField(
            model_name="diagram",
            name="model_used",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="diagram",
            name="warnings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="diagram",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="diagram",
            name="type",
            field=models.CharField(
                choices=[
                    ("flowchart", "flowchart"),
                    ("sequence", "sequence"),
                    ("state", "state"),
                    ("er", "erDiagram"),
                    ("class", "classDiagram"),
                    ("journey", "journey"),
                    ("gantt", "gantt"),
                    ("timeline", "timeline"),
                    ("pie", "pie"),
                    ("mindmap", "mindmap"),
                    ("gitGraph", "gitGraph"),
                    ("quadrant", "quadrantChart"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="diagramrevision",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
