# ai-chat-django/.github/workflows/subs-cron.yml
name: charge-subscriptions (daily)

on:
  schedule:
    # UTC! 04:20 UTC ежедневно — 4:20 в Москве
    - cron: "20 4 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  run-charges:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      LIMIT: "100"                                     # разовая порция
    steps:
      - name: Warm up Render (health check)
        run: |
          echo "GET $BACKEND_URL/healthz/"
          curl -sS --max-time 15 "$BACKEND_URL/healthz/" || true

      - name: Charge subscriptions (POST)
        run: |
          set -e
          echo "POST $BACKEND_URL/api/payment/charge-subscriptions/ limit=$LIMIT"
          curl -sS \
            --fail \
            --retry 5 \
            --retry-all-errors \
            --max-time 60 \
            -H "Content-Type: application/json" \
            -H "X-CRON-SECRET: $CRON_SECRET" \
            -d "{\"limit\": $LIMIT}" \
            "$BACKEND_URL/api/payment/charge-subscriptions/"
          echo "✓ charge job finished"

      - name: Done
        run: echo "All good ✅"
